name: PrinterMonitor
options:
  bundleIdPrefix: com.samduncan
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "16.0"
  generateEmptyDirectories: true

settings:
  base:
    SWIFT_VERSION: "6.0"
    TARGETED_DEVICE_FAMILY: "1"
    DEVELOPMENT_TEAM: ""
    ENABLE_USER_SCRIPT_SANDBOXING: NO

targets:
  PrinterMonitor:
    type: application
    platform: iOS
    sources:
      - path: PrinterMonitor
        excludes:
          - "**/.DS_Store"
      - path: Shared
        excludes:
          - "**/.DS_Store"
    settings:
      base:
        INFOPLIST_FILE: PrinterMonitor/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.samduncan.PrinterMonitor
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        SUPPORTS_MACCATALYST: NO
    info:
      path: PrinterMonitor/Info.plist
      properties:
        CFBundleDisplayName: Printer Monitor
        CFBundleShortVersionString: "1.0.0"
        CFBundleVersion: "1"
        UILaunchScreen: {}
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
        NSSupportsLiveActivities: true
    dependencies:
      - target: PrinterMonitorWidgetExtension
        embed: true

  PrinterMonitorWidgetExtension:
    type: app-extension
    platform: iOS
    sources:
      - path: PrinterMonitorWidget
        excludes:
          - "**/.DS_Store"
      - path: Shared
        excludes:
          - "**/.DS_Store"
    settings:
      base:
        INFOPLIST_FILE: PrinterMonitorWidget/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.samduncan.PrinterMonitor.widget
        SKIP_INSTALL: YES
    info:
      path: PrinterMonitorWidget/Info.plist
      properties:
        CFBundleDisplayName: Printer Widget
        CFBundleShortVersionString: "1.0.0"
        CFBundleVersion: "1"
        NSExtension:
          NSExtensionPointIdentifier: com.apple.widgetkit-extension
